{% set name = "sundials" %}
{% set version = "3.1.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: http://computation.llnl.gov/projects/{{ name }}/download/{{ name }}-{{ version }}.tar.gz
  sha256: a24d643d31ed1f31a25b102a1e1759508ce84b1e4739425ad0e18106ab471a24
build:
  number: 0

requirements:
  build:
    - cmake
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}
  host:
    - msinttypes  # [win and vc<14]
    - liblapack  # [not win]
    - suitesparse  # [not win]
  run:
    - suitesparse  # [not win]

test:
  requires:
    - cmake
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  files:
    - CMakeLists.txt
    - cvRoberts_dns.c
    - cvRoberts_klu.c
    - cvAdvDiff_bndL.c
    - cvAdvDiff_bnd_omp.c
  commands:
    - conda inspect linkages -p ${PREFIX} sundials  # [not win]
    - conda inspect objects -p ${PREFIX} sundials  # [osx]

about:
  home: http://computation.llnl.gov/casc/sundials/main.html
  license: BSD 3-Clause
  license_file: LICENSE
  summary: 'SUite of Nonlinear and DIfferential/ALgebraic equation Solvers'

extra:
  recipe-maintainers:
    - bjodah
    - jschueller
