{% set name = "sundials" %}
{% set version = "6.6.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/LLNL/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 4830d6f6943e95a6edf33a90a7181ce5bece28efe6d21e1e39ea1135708a948f

build:
  number: 0
  run_exports:
    - {{ pin_subpackage('sundials', max_pin='x.x') }}

requirements:
  build:
    - cmake
    - make   # [unix]
    - ninja
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - libblas
    - liblapack  # [not win]
    - suitesparse  # [not win]
  run:
    - suitesparse  # [not win]

test:
  commands:
    - test -f ${PREFIX}/include/sundials/sundials_band.h  # [unix]

about:
  home: https://computing.llnl.gov/projects/sundials
  license: BSD-3-Clause
  license_file: LICENSE
  summary: SUite of Nonlinear and DIfferential/ALgebraic equation Solvers

extra:
  recipe-maintainers:
    - bjodah
    - jschueller
