{% set name = "sundials" %}
{% set version = "3.1.1" %}
{% set variant = "openblas" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: http://computation.llnl.gov/projects/{{ name }}/download/{{ name }}-{{ version }}.tar.gz
  sha256: a24d643d31ed1f31a25b102a1e1759508ce84b1e4739425ad0e18106ab471a24

build:
  number: 0
  features:
    - blas_{{ variant }}  # [not win]
    - vc9  # [win and py27]
    - vc14  # [win and py>=35]
  skip: true  # [win and py>35]

requirements:
  build:
    - cmake
    - msinttypes  # [win and py<35]
    - blas 1.1 {{ variant }}  # [not win]
    - openblas 0.2.20|0.2.20.*  # [not win]
    - suitesparse  # [not win]
    - python  # [win]
    - gcc  # [linux]
  run:
    - blas 1.1 {{ variant }}  # [not win]
    - openblas 0.2.20|0.2.20.*  # [not win]
    - suitesparse  # [not win]
    - libgcc  # [linux]

test:
  requires:
    - cmake
    - python  # [win]
    - gcc  # [linux]
  files:
    - cvRoberts_dns.c
    - cvRoberts_klu.c
    - cvAdvDiff_bndL.c
    - cvAdvDiff_bnd_omp.c
  commands:
    - conda inspect linkages -p ${PREFIX} sundials  # [not win]
    - conda inspect objects -p ${PREFIX} sundials  # [osx]

about:
  home: http://computation.llnl.gov/casc/sundials/main.html
  license: BSD 3-Clause
  license_file: LICENSE
  summary: 'SUite of Nonlinear and DIfferential/ALgebraic equation Solvers'

extra:
  recipe-maintainers:
    - bjodah
    - jschueller
