{% set name = "sundials" %}
{% set version = "4.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: http://computation.llnl.gov/projects/{{ name }}/download/{{ name }}-{{ version }}.tar.gz
  sha256: 280de1c27b2360170a6f46cb3799b2aee9dff3bddbafc8b08c291a47ab258aa5

build:
  number: 1
  features:

requirements:
  build:
    - cmake
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - libblas
    - libcblas
    - msinttypes  # [win and vc<14]
    - suitesparse  # [not win]
  run:
    - suitesparse  # [not win]

test:
  requires:
    - cmake
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  files:
    - CMakeLists.txt
    - cvRoberts_dns.c
    - cvRoberts_klu.c
    - cvAdvDiff_bndL.c
    - cvAdvDiff_bnd_omp.c
  commands:
    - conda inspect linkages -p ${PREFIX} sundials  # [not win]
    - conda inspect objects -p ${PREFIX} sundials  # [osx]

about:
  home: http://computation.llnl.gov/casc/sundials/main.html
  license: BSD 3-Clause
  license_file: LICENSE
  summary: 'SUite of Nonlinear and DIfferential/ALgebraic equation Solvers'

extra:
  recipe-maintainers:
    - bjodah
    - jschueller
