{% set name = "sundials" %}
{% set version = "6.6.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/LLNL/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: e10e624e6104cbf77c3f934f5bfb2d7a7fca8fadef1d2a0f4d433ecb7ec4b71c

build:
  number: 1
  run_exports:
    - {{ pin_subpackage('sundials', max_pin='x.x') }}

requirements:
  build:
    - cmake
    - make   # [unix]
    - ninja
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - libblas
    - liblapack  # [not win]
    - suitesparse  # [not win]
  run:
    - suitesparse  # [not win]

test:
  commands:
    - test -f ${PREFIX}/include/sundials/sundials_band.h  # [unix]

about:
  home: https://computing.llnl.gov/projects/sundials
  license: BSD-3-Clause
  license_file: LICENSE
  summary: SUite of Nonlinear and DIfferential/ALgebraic equation Solvers

extra:
  recipe-maintainers:
    - bjodah
    - jschueller
