{% set name = "sundials" %}
{% set version = "7.5.0" %}

package:
  name: {{ name }}-split
  version: {{ version }}

source:
  - url: https://github.com/LLNL/{{ name }}/archive/v{{ version }}.tar.gz
    sha256: 8b5fe715009cd0f1a0ff244729c2570e3e631d3bf357495e7813b5063d4d0cf3
    folder: sundials
  - url: https://github.com/xiaoyeli/superlu_mt/archive/3d805210e95bb5b86b9ec3ade0e200714b6964dc.zip
    folder: superlu_mt
    sha256: 6b2a914209c1e007ccbfb0aa864b9782377ef45262376b611a193963e43c1972

build:
  number: 0

outputs:
  - name: {{ name }}
    script: build-sundials.sh  # [unix]
    script: bld-sundials.bat  # [win]
    run_exports:
      - {{ pin_subpackage('sundials', max_pin='x.x') }}
    requirements:
      build:
        - cmake
        - ninja
        - {{ compiler('c') }}
        - {{ stdlib("c") }}
        - {{ compiler('cxx') }}
        - {{ compiler("fortran") }}
      host:
        - libblas
        - liblapack
        - suitesparse
        - llvm-openmp-fortran  # [win]
      run:
        - suitesparse
    test:
      commands:
        - test -f ${PREFIX}/include/sundials/sundials_band.h  # [unix]
        - test -e ${PREFIX}/lib/libsundials_core${SHLIB_EXT}  # [unix]
        - test -e ${PREFIX}/lib/libsundials_core${SHLIB_EXT}  # [unix]
        - test ! -e ${PREFIX}/lib/libsundials_core.a  # [unix]
        - if not exist %LIBRARY_PREFIX%\include\sundials\sundials_band.h (exit 1)  # [win]
        - if not exist %LIBRARY_PREFIX%\bin\sundials_core.dll (exit 1)  # [win]
        - if not exist %LIBRARY_PREFIX%\lib\sundials_core.lib (exit 1)  # [win]
        - if exist %LIBRARY_PREFIX%\lib\sundials_core_static.lib (exit 1)  # [win]

  - name: {{ name }}-static
    script: build-sundials.sh  # [unix]
    script: bld-sundials.bat  # [win]
    requirements:
      build:
        - cmake
        - ninja
        - {{ compiler('c') }}
        - {{ stdlib("c") }}
        - {{ compiler('cxx') }}
        - {{ compiler("fortran") }}
      host:
        - libblas
        - liblapack
        - suitesparse
        - llvm-openmp-fortran  # [win]
      run:
        - suitesparse
    test:
      commands:
        - test -f ${PREFIX}/include/sundials/sundials_band.h  # [unix]
        - test ! -e ${PREFIX}/lib/libsundials_core${SHLIB_EXT}  # [unix]
        - test ! -e ${PREFIX}/lib/libsundials_core${SHLIB_EXT}  # [unix]
        - test -e ${PREFIX}/lib/libsundials_core.a  # [unix]
        - if not exist %LIBRARY_PREFIX%\include\sundials\sundials_band.h (exit 1)  # [win]
        - if exist %LIBRARY_PREFIX%\bin\sundials_core.dll (exit 1)  # [win]
        - if exist %LIBRARY_PREFIX%\lib\sundials_core.lib (exit 1)  # [win]
        - if not exist %LIBRARY_PREFIX%\lib\sundials_core_static.lib (exit 1)  # [win]

  - name: {{ name }}-devel
    script: build-sundials.sh  # [unix]
    script: bld-sundials.bat  # [win]
    requirements:
      build:
        - cmake
        - ninja
        - {{ compiler('c') }}
        - {{ stdlib("c") }}
        - {{ compiler('cxx') }}
        - {{ compiler("fortran") }}
      host:
        - libblas
        - liblapack
        - suitesparse
        - llvm-openmp-fortran  # [win]
      run:
        - suitesparse
    test:
      commands:
        - test -f ${PREFIX}/include/sundials/sundials_band.h  # [unix]
        - test -e ${PREFIX}/lib/libsundials_core${SHLIB_EXT}  # [unix]
        - test -e ${PREFIX}/lib/libsundials_core${SHLIB_EXT}  # [unix]
        - test -e ${PREFIX}/lib/libsundials_core.a  # [unix]
        - if not exist %LIBRARY_PREFIX%\include\sundials\sundials_band.h (exit 1)  # [win]
        - if not exist %LIBRARY_PREFIX%\bin\sundials_core.dll (exit 1)  # [win]
        - if not exist %LIBRARY_PREFIX%\lib\sundials_core.lib (exit 1)  # [win]
        - if not exist %LIBRARY_PREFIX%\lib\sundials_core_static.lib (exit 1)  # [win]

about:
  home: https://computing.llnl.gov/projects/sundials
  license: BSD-3-Clause
  license_file:
    - sundials/LICENSE
    - superlu_mt/License.txt
  summary: SUite of Nonlinear and DIfferential/ALgebraic equation Solvers

extra:
  recipe-maintainers:
    - bjodah
    - jschueller
