{% set name = "sundials" %}
{% set version = "5.5.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: http://computation.llnl.gov/projects/{{ name }}/download/{{ name }}-{{ version }}.tar.gz
  sha256: 2a755e89aab96d2ff096a4e30bf00bb162e80be20e9e99f424dccfb249098237

build:
  number: 0
  run_exports:
    - {{ pin_subpackage('sundials', max_pin='x.x') }}

requirements:
  build:
    - cmake
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - msinttypes  # [win and vc<14]
    - liblapack  # [not win]
    - suitesparse  # [not win]
  run:
    - suitesparse  # [not win]

test:
  requires:
    - cmake
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  files:
    - CMakeLists.txt
    - cvRoberts_dns.c
    - cvRoberts_klu.c
    - cvAdvDiff_bndL.c
    - cvAdvDiff_bnd_omp.c
  commands:

about:
  home: http://computation.llnl.gov/casc/sundials/main.html
  license: BSD-3-Clause
  license_file: LICENSE
  summary: SUite of Nonlinear and DIfferential/ALgebraic equation Solvers

extra:
  recipe-maintainers:
    - bjodah
    - jschueller
