{% set name = "sundials" %}
{% set version = "3.1.0" %}
{% set variant = "openblas" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: http://computation.llnl.gov/projects/{{ name }}/download/{{ name }}-{{ version }}.tar.gz
  sha256: 18d52f8f329626f77b99b8bf91e05b7d16b49fde2483d3a0ea55496ce4cdd43a

build:
  number: 201
  features:
    - blas_{{ variant }}  # [not win]
    - vc9  # [win and py27]
    - vc14  # [win and py>=35]
  skip: true  # [win and py>35]

requirements:
  build:
    - cmake
    - msinttypes  # [win and py<35]
    - blas 1.1 {{ variant }}  # [not win]
    - openblas 0.2.20|0.2.20.*  # [not win]
    - suitesparse  # [not win]
    - python  # [win]
  run:
    - blas 1.1 {{ variant }}  # [not win]
    - openblas 0.2.20|0.2.20.*  # [not win]
    - suitesparse  # [not win]

test:
  requires:
    - cmake
    - python  # [win]
  files:
    - cvRoberts_dns.c
    - cvAdvDiff_bndL.c
    - cvAdvDiff_bnd_omp.c
  commands:
    - conda inspect linkages -p ${PREFIX} sundials  # [not win]
    - conda inspect objects -p ${PREFIX} sundials  # [osx]

about:
  home: http://computation.llnl.gov/casc/sundials/main.html
  license: BSD 3-Clause
  license_file: LICENSE
  summary: 'SUite of Nonlinear and DIfferential/ALgebraic equation Solvers'

extra:
  recipe-maintainers:
    - bjodah
    - jschueller
