travis:
  secure:
    BINSTAR_TOKEN: kpYalVvFSor8TWbFY2tpkFauQc9nqjuNBwPGZhfQT99IzFcBW9gmXVnEBXXqGoy07MDL9ULUVPGGYgUjKqvm5Qz3uUwNM7Xq/AowA4bueIyyXtHhY2gWFnn3X1b4FWBNeLeaAaFzfk7HJ6hVVURkfxL4v5ZKG2EkMJA9uxrIWXvBD53kUEjGhVbZmTqCJ06lLuX9DqIrVl1DN0C037LZEVzcUN2sh82kDbL58LwSWIzu1/RaTJTJu3ZvsKULBWfkDzvrhPM8ubobDTwn65XG9D9118g2+JZb7TC0pmf5fRuKyCu0ssi3IJN64n9hXDWyvuNXBtIvFk7zb1L0qUPIs+ZqsagLhICZE89ruTd/dwnIBcTlAFoTyd/BWr7+UxNvsPausVUFHkEX3fVXj8wgyQ97pw4H/fxF/pd08sn0TR4XuuePKn43/vG+A3Sub9CDj4qI7gFs1EUGQGm286EIt02G6/x9Ri83yR1gLfmPFOxjPmoAv4j8/X6TPMOYb2wyF9OXVbio18uAiPCN5fF/mmJgDKUNAlC2MxdDnsL4KoFXVVNGfjcaeTOLOZwuV7nekGk8kQQPqTIZoNftoEahO767IBPhqr3Xwrwd4iwS7rXpJwj+hix05BL8OZpy7xHBP50GM1SwMzJNLdNFxwxV848MpIhln+H9Qz1eMp2qKAA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
